"""Score a chronumental build against treetime's published dates on ebola.

Everything in the simulation benchmark is generated by our own simulator, so a
model can look good there by fitting the generator rather than reality. The
ebola example dataset is the check against that. It has no ground truth, so
treetime's dates are used as a reference, with LSD2's agreement quoted for
scale: two independent methods landing close together is what makes a large
disagreement meaningful.

    python compare_ebola.py --chronumental /path/to/venv/bin/chronumental
    python compare_ebola.py --chronumental ... --extra "--model MyNewModel"

Reference numbers on this dataset, median absolute difference from treetime
over the 228 internal nodes both report:

    LSD2                        8.1 days   (root 2013-10-15)
    chronumental, current      12.8 days   (root 2013-12-12)
    treetime itself                    -   (root 2013-10-01)

Beating 12.8 while keeping the root near treetime's would be a real result.
Note that treetime and LSD2 disagree with each other by 24% on the clock rate,
so chasing treetime's exact numbers past that point is tuning to one reference
rather than to truth.
"""

import argparse
import datetime
import os
import shutil
import statistics
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import methods  # noqa: E402

EBOLA = "/home/theo/chron_analysis/ebola"
GENOME_LENGTH = 19006  # the alignment is 19,006 columns
DAYS_PER_YEAR = 365.25


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--chronumental", required=True,
                        help="Path to the chronumental executable to score")
    parser.add_argument("--extra", default="",
                        help="Extra flags, e.g. \"--model MyNewModel\"")
    parser.add_argument("--steps", type=int, default=2000)
    parser.add_argument("--label", default="candidate")
    args = parser.parse_args()

    work = tempfile.mkdtemp(prefix="ebola_cmp_")
    dates_out = os.path.join(work, "out.tsv")

    command = (f"{args.chronumental}"
               f" --dates {EBOLA}/ebola_data/ebola.metadata.csv"
               f" --tree {EBOLA}/2022-07-04_treetime/divergence_tree.nexus"
               f" --dates_out {dates_out} --tree_out /dev/null"
               f" --steps {args.steps}"
               f" --treat_mutation_units_as_normalised_to_genome_size {GENOME_LENGTH}"
               f" {args.extra}")
    result = subprocess.run(command, shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        print("chronumental failed:")
        print("\n".join(result.stderr.strip().split("\n")[-8:]))
        return 1

    reference = methods.parse_treetime_dates(
        os.path.join(EBOLA, "2022-07-04_treetime"))
    holder = os.path.join(work, "parsed")
    os.makedirs(holder, exist_ok=True)
    shutil.copy(dates_out, os.path.join(holder, "dates.tsv"))
    candidate = methods.parse_chronumental_dates(holder)

    # Internal nodes only: tip dates are given to the method as input, so
    # scoring them measures obedience rather than inference.
    internal = [name for name in reference
                if name in candidate and name.startswith("NODE")]
    if not internal:
        print("No internal nodes in common; did node labels survive?")
        return 1

    differences = [(candidate[n] - reference[n]) * DAYS_PER_YEAR
                   for n in internal]
    absolute = sorted(abs(d) for d in differences)
    root = candidate.get("NODE_0000001")
    root_date = (datetime.datetime(2013, 1, 1) +
                 datetime.timedelta(days=(root - 2013) * DAYS_PER_YEAR)
                 ) if root else None

    print(f"{args.label}: {len(internal)} internal nodes vs treetime")
    print(f"  median |difference|  {absolute[len(absolute) // 2]:6.1f} days")
    print(f"  mean signed          {statistics.fmean(differences):+6.1f} days")
    print(f"  90th percentile      {absolute[int(0.9 * len(absolute))]:6.1f} days")
    print(f"  max                  {absolute[-1]:6.1f} days")
    if root_date:
        print(f"  root date            {root_date:%Y-%m-%d}"
              f"   (treetime 2013-10-01, LSD2 2013-10-15)")
    print("  reference: LSD2 median 8.1 d, current chronumental 12.8 d")
    return 0


if __name__ == "__main__":
    sys.exit(main())
